# Generated by Django 4.2.19 on 2025-03-17 09:57

from django.db import migrations, models
import metagetter.storage_backends


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(storage=metagetter.storage_backends.PublicMediaStorage(), upload_to='')),
            ],
        ),
    ]
