# Generated by Django 4.2.19 on 2025-03-11 12:36

from django.db import migrations, models
import metagetter.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(storage=metagetter.storage_backends.PublicMediaStorage(), upload_to=''),
        ),
    ]
