# Generated by Django 4.2.19 on 2025-06-30 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_drf_filepond', '0010_temp_chunked_biginteger'),
        ('core', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='django_drf_filepond.storedupload')),
            ],
        ),
    ]
