# Generated by Django 4.2.19 on 2025-06-30 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_userimages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userimages',
            options={'verbose_name': 'User Image', 'verbose_name_plural': 'User Images'},
        ),
        migrations.AddField(
            model_name='userimages',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='userimages',
            name='user',
            field=models.ForeignKey(default=77, on_delete=django.db.models.deletion.CASCADE, related_name='images', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
