# Generated by Django 4.2.19 on 2025-06-30 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_userimages_options_userimages_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userimages',
            name='upload_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
