# Generated by Django 4.2.19 on 2025-06-30 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_drf_filepond', '0010_temp_chunked_biginteger'),
        ('core', '0005_userimages_upload_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimages',
            name='image',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_drf_filepond.storedupload'),
        ),
    ]
