# Generated by Django 4.2.19 on 2025-06-30 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_userimages_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userimages',
            name='upload_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
