# Generated by Django 4.2.19 on 2025-10-09 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_imagemetadata_userimages_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemetadata',
            name='downloaded',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='imagemetadata',
            name='edited',
            field=models.BooleanField(null=True),
        ),
    ]
