# Generated by Django 4.2.19 on 2026-03-02 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_questions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questions',
            options={'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
    ]
