# Generated by Django 4.2.19 on 2026-03-03 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_termsandcondtions_usertermsacceptance'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TermsAndCondtions',
            new_name='TermsAndConditions',
        ),
    ]
