# Generated by Django 4.2.19 on 2026-03-07 18:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_termsandcondtions_termsandconditions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='termsandconditions',
            options={'verbose_name': 'Terms and Conditions', 'verbose_name_plural': 'Terms and Conditions'},
        ),
        migrations.AddField(
            model_name='profile',
            name='public_id_number',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
