# Generated by Django 4.2.19 on 2026-03-07 18:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_termsandconditions_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='public_id_number',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
