# Generated by Django 4.2.19 on 2026-03-12 14:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_profile_public_id_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='public_id_number',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
