# Generated by Django 4.2.19 on 2026-03-17 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_pivacypolicy_alter_profile_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PivacyPolicy',
            new_name='PrivacyPolicy',
        ),
    ]
